name: 🐛 Bug Report (Product Issue)
description: Report a bug with a BrightCom product (not documentation)
title: "[BUG] "
labels: ["bug", "product-issue"]
body:
  - type: markdown
    attributes:
      value: |
        **Note:** This template is for reporting bugs with BrightCom products themselves, not documentation issues.
        For documentation problems, please use the "Documentation Issue" template instead.

  - type: dropdown
    id: product
    attributes:
      label: BrightCom Product
      description: Which product is experiencing the issue?
      options:
        - "BRC Connect"
        - "BRC Logistics"
        - "BRC Core"
        - "BRC Retail"
        - "BRC Bonus"
        - "BRC GDPR"
        - "BRC Drop Shipment"
        - "BRC Extended IC"
        - "BRC Pleo"
    validations:
      required: true

  - type: input
    id: product-version
    attributes:
      label: Product Version
      description: What version of the product are you using?
      placeholder: "e.g., 23.0.20451.0"

  - type: input
    id: bc-version
    attributes:
      label: Business Central Version
      description: What version of Business Central are you using?
      placeholder: "e.g., Business Central 2024 Wave 1"

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Please describe the issue you're experiencing
      placeholder: "When I try to sync data, I get an error message..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Enter...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "The data should sync successfully without errors"

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "I receive error message XYZ and the sync fails"

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages or Screenshots
      description: Please include any error messages, screenshots, or relevant logs
      placeholder: "Paste error messages here or drag and drop screenshots"

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severely does this issue affect your work?
      options:
        - "Low - Minor inconvenience"
        - "Medium - Affects some functionality"
        - "High - Blocks important tasks"
        - "Critical - System unusable"
    validations:
      required: true