name: 💡 Feature Request
description: Suggest a new feature for BrightCom products or documentation
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
body:
  - type: dropdown
    id: request-type
    attributes:
      label: Type of Feature Request
      description: Is this for a product feature or documentation improvement?
      options:
        - "Product feature (new functionality)"
        - "Documentation feature (site improvement)"
        - "Both product and documentation"
    validations:
      required: true

  - type: dropdown
    id: product
    attributes:
      label: BrightCom Product (if applicable)
      description: Which product would this feature be for?
      options:
        - "BRC Connect"
        - "BRC Logistics"
        - "BRC Core"
        - "BRC Retail"
        - "BRC Bonus"
        - "BRC GDPR"
        - "BRC Drop Shipment"
        - "BRC Extended IC"
        - "BRC Pleo"
        - "Partner Solutions"
        - "Documentation site"
        - "Multiple products"
        - "New product idea"

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please describe the feature you'd like to see
      placeholder: "I would like the ability to automatically sync customer data every hour..."
    validations:
      required: true

  - type: textarea
    id: business-case
    attributes:
      label: Business Case or Problem
      description: What problem would this feature solve? Why is it needed?
      placeholder: "Currently, we have to manually sync data which is time-consuming and error-prone..."

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this feature should work?
      placeholder: "Add a scheduled job option in the setup page that allows users to configure automatic sync intervals..."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "We could use Power Automate, but a built-in solution would be more reliable..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, mockups, or examples that might be helpful
      placeholder: "Similar to how [other system] handles this feature..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve efficiency"
        - "High - Significant business value"
        - "Critical - Essential for our operations"
    validations:
      required: true